import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  cardWrapper: {
    width: "100%",
    height: "95%",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
  },
  card: {
    width: "100%",
    minWidth: 400,
    maxWidth: 400,
    height: "100%",
    borderRadius: 20,
    backgroundColor: "transparent",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.4,
    shadowRadius: 6.68,
    elevation: 15,
    position: "relative",
    overflow: "hidden",
  },
  image: {
    flex: 1,
    width: "100%",
    height: "100%",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  imageStyle: {
    width: "100%",
    height: "100%",
    resizeMode: "stretch",
    borderRadius: 0,
  },
  cardInner: {
    flex: 1,
    justifyContent: "flex-end",
  },
  contentContainer: {
    paddingHorizontal: 10,
    paddingTop: 5,
    paddingBottom: 20,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 20,
  },
  name: {
    fontSize: 30,
    color: "white",
    fontWeight: "bold",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 3,
    textAlign: "left",
  },
  bio: {
    fontSize: 18,
    color: "white",
    lineHeight: 24,
    textAlign: "left",
  },
  fadedBio: {
    opacity: 0.75,
  },
  pagination: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 8,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  pageIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ccc",
    marginHorizontal: 4,
  },
  activeIndicator: {
    backgroundColor: "white",
  },
  swipeAreaLeft: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "50%",
    height: "100%",
    zIndex: 10,
  },
  swipeAreaRight: {
    position: "absolute",
    top: 0,
    right: 0,
    width: "50%",
    height: "100%",
    zIndex: 10,
  },
  centeredContent: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: "white",
    marginTop: 25,
    marginBottom: 10,
    textShadowColor: "#000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    textAlign: "center",
  },
  castCrewContainer: {
    flexDirection: "row", // Arrange Cast and Crew lists side by side
    justifyContent: "space-between",
    alignItems: "flex-start",
    width: "100%",
    height: "82%",
    paddingHorizontal: 10,
  },
  scrollListContainer: {
    width: "48%", // Ensure each list takes up half the width
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  autoScrollVertical: {
    height: 100, // Fixed height to define the scrolling area
    width: "80%",
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#ccc",
    marginVertical: 5, // Margin to separate title from the list
    textAlign: "center",
  },
  member: {
    fontSize: 18,
    color: "white",
    marginBottom: 5,
    textAlign: "center",
  },
  review: {
    fontSize: 16,
    color: "white",
    marginVertical: 5,
    textAlign: "center",
  },
});
